# Generated by Django 5.2 on 2026-09-15 00:00
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('STAFF', 'Staff'), ('TRANSPORT', 'Transport'), ('MAINTENANCE', 'Maintenance'), ('BANK_FEES', 'Bank Fees'), ('SOFTWARE', 'Software'), ('MARKETING', 'Marketing'), ('CLEANING', 'Cleaning'), ('OTHER', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('POS', 'POS/Card'), ('MOBILE_MONEY', 'Mobile Money'), ('OTHER', 'Other')], default='CASH', max_length=25)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='APPROVED', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='pharmacy.pharmacybrand')),
            ],
            options={
                'db_table': 'expense',
                'ordering': ('-expense_date', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['pharmacy', 'expense_date'], name='expense_pharmac_77a4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['pharmacy', 'category'], name='expense_pharmac_7120fa_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', 'expense_date'], name='expense_status_9d0f2b_idx'),
        ),
    ]
