# Generated by Django 5.0.6 on 2026-09-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='expense_pharmac_e84be3_idx',
            old_name='expense_pharmac_77a4ff_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expense_pharmac_23138e_idx',
            old_name='expense_pharmac_7120fa_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expense_status_c2c679_idx',
            old_name='expense_status_9d0f2b_idx',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('STAFF', 'Staff'), ('TRANSPORT', 'Transport'), ('MAINTENANCE', 'Maintenance'), ('BANK_FEES', 'Bank Fees'), ('SOFTWARE', 'Software'), ('MARKETING', 'Marketing'), ('CLEANING', 'Cleaning'), ('OTHER', 'Other')], db_index=True, max_length=30),
        ),
    ]
