# Generated by Django 6.0.8 on 2026-08-25 21:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('business_email', models.EmailField(blank=True, default='', max_length=255)),
                ('business_phone', models.CharField(blank=True, default='', max_length=20)),
                ('website', models.URLField(blank=True, default='')),
                ('address_line_1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('lga', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('location', models.JSONField()),
                ('pharmacy_type', models.CharField(choices=[('COMMUNITY_PHARMACY', 'Community Pharmacy'), ('HOSPITAL_PHARMACY', 'Hospital Pharmacy'), ('CLINIC_PHARMACY', 'Clinic Pharmacy'), ('WHOLESALE_PHARMACY', 'Wholesale Pharmacy'), ('MEDICAL_STORE', 'Medical Store'), ('OTHER', 'Other')], default='COMMUNITY_PHARMACY', max_length=30)),
                ('years_in_operation', models.PositiveIntegerField(default=0)),
                ('cac_registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('cac_registration_type', models.CharField(blank=True, default='', max_length=100)),
                ('pcn_premises_registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('pcn_license_number', models.CharField(blank=True, default='', max_length=100)),
                ('pcn_issue_date', models.DateField(blank=True, null=True)),
                ('pcn_expiry_date', models.DateField(blank=True, null=True)),
                ('nafdac_registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('nafdac_certificate_number', models.CharField(blank=True, default='', max_length=100)),
                ('nafdac_expiry_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_VERIFICATION', 'Pending Verification'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='DRAFT', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(limit_choices_to={'role': 'PHARMACY_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_pharmacy_brand', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'SUPER_ADMIN'), ('role', 'PLATFORM_ADMIN'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_pharmacy_brands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_brand',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyBrandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='pharmacy/brands/%Y/%m/%d/')),
                ('image_type', models.CharField(choices=[('FRONT_VIEW', 'Front View'), ('INTERIOR', 'Interior'), ('PHARMACY_SIGN', 'Pharmacy Sign'), ('COUNTER', 'Counter'), ('DOCUMENT', 'Document'), ('OTHER', 'Other')], default='FRONT_VIEW', max_length=30)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pharmacy.pharmacybrand')),
            ],
            options={
                'db_table': 'pharmacy_brand_image',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pharmacybrand',
            index=models.Index(fields=['owner'], name='pharmacy_br_owner_i_80bf26_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacybrand',
            index=models.Index(fields=['verification_status'], name='pharmacy_br_verific_962726_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacybrand',
            index=models.Index(fields=['brand_name'], name='pharmacy_br_brand_n_64a446_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacybrand',
            index=models.Index(fields=['cac_registration_number'], name='pharmacy_br_cac_reg_b68680_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacybrand',
            index=models.Index(fields=['pcn_license_number'], name='pharmacy_br_pcn_lic_2bac55_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacybrand',
            index=models.Index(fields=['nafdac_registration_number'], name='pharmacy_br_nafdac__987cdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacybrandimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('brand',), name='unique_primary_brand_image'),
        ),
    ]
