# Generated by Django 5.1.15 on 2026-08-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_pharmacybrand_location_pharmacybrand_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacybrand',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pharmacybrand',
            name='longitude',
        ),
        migrations.AddField(
            model_name='pharmacybrand',
            name='location',
            # Use a TextField in this migration so it can run on SQLite during development.
            # The app-level model will use PointField when PostGIS is configured.
            field=models.TextField(blank=True, null=True),
        ),
    ]
