# Generated by Django 5.1.15 on 2026-08-25 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_migrate_latlng_to_location'),
        ('pharmacy', '0003_remove_pharmacybrand_latitude_and_more'),
    ]

    operations = [
    ]
