# Generated by Django 5.1.15 on 2026-08-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_merge_20260825_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacybrand',
            name='location_tmp',
        ),
        migrations.RemoveField(
            model_name='pharmacybrand',
            name='website',
        ),
    ]
