# Generated by Django 5.1.15 on 2026-08-26 13:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_remove_pharmacybrand_location_tmp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacybrand',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
