# Generated by Django 5.1.15 on 2026-08-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_owner_protect'),
        ('pharmacy', '0006_alter_pharmacybrand_location'),
    ]

    operations = [
    ]
