# Generated by Django 5.1.15 on 2026-08-26 14:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_merge_20260826_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacymembership',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
