# Generated by Django 5.1.15 on 2026-08-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_alter_pharmacymembership_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pharmacybrandimage',
            name='unique_primary_brand_image',
        ),
        migrations.AddConstraint(
            model_name='pharmacybrandimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('brand', 'image_type'), name='unique_primary_brand_image_per_type'),
        ),
    ]
