# Generated by Django 5.1.15 on 2026-08-27 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_remove_pharmacybrandimage_unique_primary_brand_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacybrand',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacybrand',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_pharmacy_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacybrand',
            name='review_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacybrand',
            name='review_started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_pharmacy_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacybrand',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacybrand',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_pharmacy_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacybrand',
            name='suspension_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pharmacybrandimage',
            name='image_type',
            field=models.CharField(choices=[('EXTERIOR', 'Exterior'), ('FRONT_VIEW', 'Front View'), ('INTERIOR', 'Interior'), ('PHARMACY_SIGN', 'Pharmacy Sign'), ('COUNTER', 'Counter'), ('DOCUMENT', 'Document'), ('OTHER', 'Other')], default='FRONT_VIEW', max_length=30),
        ),
        migrations.CreateModel(
            name='PharmacyVerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='pharmacy/verification/%Y/%m/%d/')),
                ('document_type', models.CharField(choices=[('CAC_DOCUMENT', 'CAC Document'), ('PCN_DOCUMENT', 'PCN Document'), ('NAFDAC_DOCUMENT', 'NAFDAC Document')], max_length=30)),
                ('review_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='pharmacy.pharmacybrand')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyVerificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEW_STARTED', 'Review Started'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('REINSTATED', 'Reinstated')], max_length=30)),
                ('reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pharmacy_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_history', to='pharmacy.pharmacybrand')),
            ],
        ),
    ]
