# Generated by Django 5.1.15 on 2026-08-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_pharmacybrand_rejected_at_pharmacybrand_rejected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacymembership',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
