# Generated by Django 5.1.15 on 2026-09-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_add_rejection_reason_to_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacybrand',
            name='closetime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacybrand',
            name='opnetime',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
