# Generated by Django 5.1.15 on 2026-09-06 22:43

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_pharmacybrand_closetime_pharmacybrand_opnetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pharmacybrand',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('brand_name')), name='unique_pharmacy_brand_name_ci'),
        ),
    ]
