# Generated by Django 5.1.15 on 2026-09-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_pharmacybrand_unique_pharmacy_brand_name_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacybrand',
            name='pharmacy_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
