# Generated by Django 5.1.15 on 2026-09-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_pharmacybrand_pharmacy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacybrand',
            name='brand_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
