# Generated by Django 5.1.15 on 2026-08-28 13:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
        ('pharmacy', '0011_add_rejection_reason_to_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyInventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling price in NGN', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Whether this item is published to Smart Medicine Finder')),
                ('published_at', models.DateTimeField(blank=True, help_text='When this item was published', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_items', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(help_text='The medicine/product definition', on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_inventory', to='medicine.medicine')),
                ('pharmacy', models.ForeignKey(help_text='The pharmacy that carries this item', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='pharmacy.pharmacybrand')),
                ('published_by', models.ForeignKey(blank=True, help_text='User who published this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_inventory_item',
                'ordering': ['pharmacy', 'medicine'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, help_text='Batch/lot number from supplier', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Available quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('expiry_date', models.DateField(db_index=True, help_text='Batch expiry date')),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit (supplier cost)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(help_text='The inventory item this batch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.pharmacyinventoryitem')),
            ],
            options={
                'db_table': 'inventory_batch',
                'ordering': ['inventory_item', 'expiry_date'],
            },
        ),
        migrations.AddIndex(
            model_name='pharmacyinventoryitem',
            index=models.Index(fields=['pharmacy', 'status'], name='pharmacy_in_pharmac_360951_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinventoryitem',
            index=models.Index(fields=['pharmacy', 'is_published'], name='pharmacy_in_pharmac_7b3e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinventoryitem',
            index=models.Index(fields=['is_published', 'status'], name='pharmacy_in_is_publ_b52d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinventoryitem',
            index=models.Index(fields=['created_at'], name='pharmacy_in_created_6cbf0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacyinventoryitem',
            unique_together={('pharmacy', 'medicine')},
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['inventory_item', 'expiry_date'], name='inventory_b_invento_ac8461_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['expiry_date'], name='inventory_b_expiry__96c551_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorybatch',
            unique_together={('inventory_item', 'batch_number')},
        ),
    ]
