# Generated by Django 5.1.15 on 2026-09-01 14:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('pharmacy', '0011_add_rejection_reason_to_membership'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_returned', models.PositiveIntegerField(help_text='Quantity being returned', validators=[django.core.validators.MinValueValidator(1)])),
                ('condition', models.CharField(choices=[('SELLABLE', 'Sellable - No Issues'), ('DAMAGED', 'Damaged - Cannot Resell'), ('QUARANTINED', 'Quarantined - Pending Inspection')], help_text='Condition of returned item', max_length=20)),
                ('reason', models.CharField(blank=True, help_text="Customer's reason for return (CUSTOMER_COMPLAINT, DEFECTIVE, QUALITY_ISSUE, etc.)", max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this return')),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_REVIEW', max_length=20)),
                ('disposition', models.CharField(blank=True, choices=[('RETURNED_TO_STOCK', 'Returned to Sellable Stock'), ('QUARANTINED_PENDING', 'Quarantined Pending Decision'), ('MARKED_DAMAGED', 'Marked as Damaged'), ('DISPOSED', 'Disposed')], help_text='How the return was disposed', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_customer_return',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity on hold', validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.CharField(help_text='Reason for hold (CUSTOMER_RETURN, QUALITY_ISSUE, INSPECTION_PENDING, etc.)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('status', models.CharField(choices=[('ON_HOLD', 'On Hold'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], db_index=True, default='ON_HOLD', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('RETURN_TO_STOCK', 'Return to Sellable Stock'), ('MARK_DAMAGED', 'Mark as Damaged'), ('MARK_EXPIRED', 'Mark as Expired'), ('WRITE_OFF', 'Write Off'), ('OTHER', 'Other')], help_text='How the hold was resolved', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, help_text='Type of parent transaction (CUSTOMER_RETURN, etc.)', max_length=50, null=True)),
                ('reference_id', models.UUIDField(blank=True, db_index=True, help_text='ID of parent transaction', null=True)),
            ],
            options={
                'db_table': 'inventory_hold',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_quantity', models.PositiveIntegerField(help_text='Quantity per system at count start')),
                ('expected_quantity_captured_at', models.DateTimeField(auto_now_add=True, help_text='When expected quantity was captured')),
                ('counted_quantity', models.PositiveIntegerField(blank=True, help_text='Physical quantity counted', null=True)),
                ('counted_at', models.DateTimeField(blank=True, help_text='When the count was performed', null=True)),
                ('difference', models.IntegerField(blank=True, help_text='counted_quantity - expected_quantity', null=True)),
                ('discrepancy_type', models.CharField(blank=True, choices=[('NO_DISCREPANCY', 'Quantity Matches'), ('SHORTAGE', 'Shortage - Fewer Units'), ('OVERAGE', 'Overage - Extra Units')], help_text='Type of discrepancy', max_length=20, null=True)),
                ('reason_for_discrepancy', models.CharField(blank=True, help_text='Reason for discrepancy (INVENTORY_ERROR, THEFT, DATA_ENTRY, etc.)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Investigation notes')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Count In Progress'), ('PENDING_APPROVAL', 'Pending Manager Approval'), ('APPROVED', 'Approved'), ('RECONCILED', 'Reconciled'), ('CANCELLED', 'Cancelled')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the count was approved', null=True)),
                ('approval_notes', models.TextField(blank=True, help_text='Approval notes')),
                ('reconciled_at', models.DateTimeField(blank=True, help_text='When reconciliation was completed', null=True)),
                ('resulting_movement_id', models.UUIDField(blank=True, help_text='ID of resulting StockMovement (if any)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_stock_reconciliation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(
                check=models.Q(quantity__gte=0),
                name='batch_quantity_non_negative',
            ),
        ),
        migrations.AddField(
            model_name='customerreturn',
            name='batch',
            field=models.ForeignKey(help_text='The batch being returned', on_delete=django.db.models.deletion.PROTECT, related_name='customer_returns', to='inventory.inventorybatch'),
        ),
        migrations.AddField(
            model_name='customerreturn',
            name='initiated_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who initiated the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerreturn',
            name='inventory_item',
            field=models.ForeignKey(help_text='The inventory item being returned', on_delete=django.db.models.deletion.PROTECT, related_name='customer_returns', to='inventory.pharmacyinventoryitem'),
        ),
        migrations.AddField(
            model_name='customerreturn',
            name='pharmacy',
            field=models.ForeignKey(help_text='The pharmacy processing this return', on_delete=django.db.models.deletion.PROTECT, related_name='customer_returns', to='pharmacy.pharmacybrand'),
        ),
        migrations.AddField(
            model_name='customerreturn',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Manager who approved/rejected the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerreturn',
            name='sale',
            field=models.ForeignKey(help_text='The original sale', on_delete=django.db.models.deletion.PROTECT, related_name='customer_returns', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='customerreturn',
            name='sale_item',
            field=models.ForeignKey(help_text='The original sale item', on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.saleitem'),
        ),
        migrations.AddField(
            model_name='inventoryhold',
            name='batch',
            field=models.ForeignKey(help_text='The batch on hold', on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='inventory.inventorybatch'),
        ),
        migrations.AddField(
            model_name='inventoryhold',
            name='initiated_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated the hold', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryhold',
            name='inventory_item',
            field=models.ForeignKey(help_text='The inventory item', on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='inventory.pharmacyinventoryitem'),
        ),
        migrations.AddField(
            model_name='inventoryhold',
            name='pharmacy',
            field=models.ForeignKey(help_text='The pharmacy', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_holds', to='pharmacy.pharmacybrand'),
        ),
        migrations.AddField(
            model_name='inventoryhold',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='User who resolved the hold', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager who approved the count', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='batch',
            field=models.ForeignKey(help_text='The batch being counted', on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='inventory.inventorybatch'),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='counted_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the count', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='inventory_item',
            field=models.ForeignKey(help_text='The inventory item', on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='inventory.pharmacyinventoryitem'),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='pharmacy',
            field=models.ForeignKey(help_text='The pharmacy', on_delete=django.db.models.deletion.PROTECT, related_name='stock_reconciliations', to='pharmacy.pharmacybrand'),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, help_text='User who performed reconciliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customerreturn',
            index=models.Index(fields=['pharmacy', 'created_at'], name='inventory_c_pharmac_049c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreturn',
            index=models.Index(fields=['pharmacy', 'status'], name='inventory_c_pharmac_b86002_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreturn',
            index=models.Index(fields=['sale', 'created_at'], name='inventory_c_sale_id_6e5412_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreturn',
            index=models.Index(fields=['status', 'created_at'], name='inventory_c_status_501322_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreturn',
            index=models.Index(fields=['inventory_item', 'created_at'], name='inventory_c_invento_82c086_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryhold',
            index=models.Index(fields=['batch', 'status'], name='inventory_h_batch_i_d42bed_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryhold',
            index=models.Index(fields=['pharmacy', 'created_at'], name='inventory_h_pharmac_b6ac48_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryhold',
            index=models.Index(fields=['status', 'created_at'], name='inventory_h_status_0cba07_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryhold',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_h_referen_6365dc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreconciliation',
            index=models.Index(fields=['pharmacy', 'created_at'], name='inventory_s_pharmac_561e61_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreconciliation',
            index=models.Index(fields=['pharmacy', 'status'], name='inventory_s_pharmac_a016da_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreconciliation',
            index=models.Index(fields=['batch', 'created_at'], name='inventory_s_batch_i_dc5009_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreconciliation',
            index=models.Index(fields=['status', 'created_at'], name='inventory_s_status_665354_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockreconciliation',
            constraint=models.CheckConstraint(
                check=models.Q(counted_quantity__isnull=True) | models.Q(difference__isnull=False),
                name='count_implies_difference',
            ),
        ),
    ]
