# Generated by Django 5.1.15 on 2026-09-02 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customerreturn_inventoryhold_stockreconciliation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyinventoryitem',
            name='unpublished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyinventoryitem',
            name='unpublished_by',
            field=models.ForeignKey(blank=True, help_text='User who unpublished this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unpublished_inventory_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
