# Generated by Django 5.1.15 on 2026-09-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_pharmacyinventoryitem_unpublished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyinventoryitem',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0, help_text='Minimum sellable quantity before this item is low stock'),
        ),
    ]
