# Generated by Django 5.1.15 on 2026-08-28 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generic_name', models.CharField(db_index=True, help_text='Generic/active ingredient name (e.g., Paracetamol)', max_length=255)),
                ('brand_name', models.CharField(blank=True, db_index=True, help_text='Brand name (e.g., Panadol). Can be blank for generic-only.', max_length=255)),
                ('strength', models.CharField(db_index=True, help_text='Strength (e.g., 500mg, 250mg/5ml)', max_length=100)),
                ('dosage_form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('LOTION', 'Lotion'), ('SUSPENSION', 'Suspension'), ('SOLUTION', 'Solution'), ('POWDER', 'Powder'), ('PATCH', 'Patch'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('route', models.CharField(choices=[('ORAL', 'Oral'), ('INTRAVENOUS', 'Intravenous'), ('INTRAMUSCULAR', 'Intramuscular'), ('SUBCUTANEOUS', 'Subcutaneous'), ('TOPICAL', 'Topical'), ('RECTAL', 'Rectal'), ('INHALED', 'Inhaled'), ('INTRANASAL', 'Intranasal'), ('OTHER', 'Other')], db_index=True, default='ORAL', max_length=30)),
                ('manufacturer', models.CharField(blank=True, help_text='Manufacturer name', max_length=255)),
                ('pack_size', models.PositiveIntegerField(default=1, help_text='Quantity per pack (e.g., 10 tablets per strip)')),
                ('pack_size_unit', models.CharField(choices=[('UNIT', 'Unit'), ('STRIP', 'Strip'), ('PACK', 'Pack'), ('BOTTLE', 'Bottle'), ('VIAL', 'Vial'), ('TUBE', 'Tube'), ('JAR', 'Jar'), ('ML', 'Milliliter'), ('L', 'Liter'), ('G', 'Gram'), ('KG', 'Kilogram'), ('MG', 'Milligram')], default='UNIT', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Additional information about this medicine')),
                ('nafdac_registration', models.CharField(blank=True, help_text='NAFDAC registration number if applicable', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medicines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medicine',
                'ordering': ['generic_name', 'brand_name', 'strength'],
                'indexes': [models.Index(fields=['generic_name', 'strength', 'dosage_form'], name='medicine_generic_34da80_idx'), models.Index(fields=['brand_name'], name='medicine_brand_n_982ee3_idx'), models.Index(fields=['created_at'], name='medicine_created_02ee04_idx')],
            },
        ),
    ]
