# Generated by Django 5.0.6 on 2026-09-12 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
        ('pharmacy', '0015_alter_pharmacybrand_brand_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['pharmacy', 'generic_name', 'brand_name', 'strength']},
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='medicine_generic_34da80_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='medicine_brand_n_982ee3_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='medicine_created_02ee04_idx',
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(blank=True, help_text='The pharmacy that owns/manages this medicine', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharmacy.pharmacybrand'),
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('pharmacy', 'generic_name', 'brand_name', 'strength', 'dosage_form')},
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['pharmacy', 'generic_name', 'strength', 'dosage_form'], name='medicine_pharmac_194288_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['pharmacy', 'brand_name'], name='medicine_pharmac_e196ab_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['pharmacy', 'created_at'], name='medicine_pharmac_f00bc5_idx'),
        ),
    ]
