# Generated by Django 5.0.6 on 2026-09-25 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_assign_legacy_medicines_to_pharmacies'),
        ('pharmacy', '0015_alter_pharmacybrand_brand_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['generic_name', 'brand_name', 'strength']},
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='medicine_pharmac_194288_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='medicine_pharmac_e196ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='medicine_pharmac_f00bc5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='medicine',
            name='created_by_pharmacy',
            field=models.ForeignKey(blank=True, help_text='Pharmacy that originally submitted this global medicine record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalog_medicines', to='pharmacy.pharmacybrand'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='source',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PUBLIC_DATABASE', 'Public Database'), ('PHARMACY', 'Pharmacy')], db_index=True, default='ADMIN', help_text='Origin of the medicine record: admin, public database, or pharmacy submission.', max_length=30),
        ),
        migrations.AddField(
            model_name='medicine',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='UNVERIFIED', help_text='Verification state for the global catalog record.', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(blank=True, help_text='Legacy or source pharmacy association for migrated records; the global medicine catalog is not owned by a single pharmacy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_medicines', to='pharmacy.pharmacybrand'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['generic_name', 'strength', 'dosage_form'], name='medicine_generic_34da80_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['brand_name'], name='medicine_brand_n_982ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['source', 'verification_status'], name='medicine_source_65918b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['created_by', 'created_at'], name='medicine_created_e820b5_idx'),
        ),
    ]
