# Generated by Django 6.0.8 on 2026-08-25

import uuid

import django.db.models.deletion
from django.db import migrations, models


def normalize_pharmacy_brand_values(apps, schema_editor):
    User = apps.get_model('auth_app', 'User')
    for user in User.objects.all():
        raw_value = getattr(user, 'pharmacy_brand', None)
        if not raw_value:
            continue
        try:
            uuid.UUID(str(raw_value))
        except (TypeError, ValueError, AttributeError):
            user.pharmacy_brand = None
            user.save(update_fields=['pharmacy_brand'])


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('auth_app', '0002_user_approved_at_user_approved_by_user_is_approved_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_pharmacy_brand_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='pharmacy_brand',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='owned_users',
                to='pharmacy.pharmacybrand',
            ),
        ),
    ]
