# Generated by Django 5.0.6 on 2026-09-14 22:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_pharmacyinventoryitem_reorder_level'),
        ('medicine', '0003_assign_legacy_medicines_to_pharmacies'),
        ('pharmacy', '0015_alter_pharmacybrand_brand_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PARTIALLY_RECEIVED', 'Partially received'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchases', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='pharmacy.pharmacybrand')),
            ],
            options={
                'db_table': 'procurement_purchase',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_ordered', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.pharmacyinventoryitem')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='medicine.medicine')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchase')),
            ],
            options={
                'db_table': 'procurement_purchase_item',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='inventory.inventorybatch')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='procurement.purchaseitem')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_purchase_receipt',
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('registration_information', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suppliers', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='pharmacy.pharmacybrand')),
            ],
            options={
                'db_table': 'procurement_supplier',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='procurement.supplier'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.UniqueConstraint(fields=('purchase', 'medicine'), name='unique_medicine_per_purchase'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['purchase_item', 'received_at'], name='procurement_purchas_a28b04_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['pharmacy', 'status'], name='procurement_pharmac_551acc_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'name'), name='unique_supplier_name_per_pharmacy'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['pharmacy', 'status', 'created_at'], name='procurement_pharmac_18e467_idx'),
        ),
    ]
