# Generated by Django 5.1.15 on 2026-08-30 13:30

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('pharmacy', '0011_add_rejection_reason_to_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('customer_type', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('REGISTERED', 'Registered'), ('CORPORATE', 'Corporate')], default='WALK_IN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(help_text='The pharmacy this customer is registered with', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='pharmacy.pharmacybrand')),
            ],
            options={
                'db_table': 'sales_customer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('VOIDED', 'Voided')], db_index=True, default='DRAFT', max_length=20)),
                ('receipt_number', models.CharField(db_index=True, help_text='Unique receipt/invoice number', max_length=100, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of line totals before discount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sale-level discount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount if applicable', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total = subtotal - discount + tax', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Payment status (not external transaction verification)', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('POS', 'POS/Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('OTHER', 'Other')], help_text='How the sale was paid', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount actually paid', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this sale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the sale was completed', null=True)),
                ('voided_at', models.DateTimeField(blank=True, help_text='When the sale was voided', null=True)),
                ('void_reason', models.TextField(blank=True, help_text='Reason for voiding')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this sale (draft)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='The customer (optional, for walk-ins)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.customer')),
                ('pharmacy', models.ForeignKey(help_text='The pharmacy making this sale', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='pharmacy.pharmacybrand')),
                ('sold_by', models.ForeignKey(blank=True, help_text='User who completed this sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_completed', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, help_text='User who voided this sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_sale',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity sold', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of sale (preserved for history)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount on this line item', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Total for this line = (quantity * unit_price) - line_discount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(help_text='The inventory item being sold', on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.pharmacyinventoryitem')),
                ('sale', models.ForeignKey(help_text='The sale this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'db_table': 'sales_sale_item',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItemBatchAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity consumed from this batch', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(help_text='The batch allocated', on_delete=django.db.models.deletion.PROTECT, related_name='sale_allocations', to='inventory.inventorybatch')),
                ('sale_item', models.ForeignKey(help_text='The sale item being allocated', on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations_rel', to='sales.saleitem')),
            ],
            options={
                'db_table': 'sales_sale_item_batch_allocation',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('SALE', 'Sale'), ('VOID', 'Void/Reversal'), ('RECEIVE', 'Receive from Supplier'), ('ADJUSTMENT', 'Manual Adjustment')], db_index=True, help_text='Type of stock movement', max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Quantity change (negative for sales, positive for receipts)')),
                ('notes', models.TextField(blank=True, help_text='Additional context about this movement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(help_text='The specific batch', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.inventorybatch')),
                ('inventory_item', models.ForeignKey(help_text='The inventory item', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.pharmacyinventoryitem')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who initiated this movement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(help_text="The pharmacy's stock", on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='pharmacy.pharmacybrand')),
                ('sale', models.ForeignKey(blank=True, help_text='Sale reference if this is a SALE movement', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='sales.sale')),
                ('sale_item', models.ForeignKey(blank=True, help_text='SaleItem reference if this is a SALE movement', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='sales.saleitem')),
            ],
            options={
                'db_table': 'sales_stock_movement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['pharmacy', 'customer_type'], name='sales_custo_pharmac_a93b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='sales_custo_phone_n_2cfbb3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='sales_custo_email_b3bee2_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['pharmacy', 'status', 'created_at'], name='sales_sale_pharmac_9a3ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['pharmacy', 'created_at'], name='sales_sale_pharmac_ff07d1_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', 'created_at'], name='sales_sale_status_23c89c_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['receipt_number'], name='sales_sale_receipt_f5ff95_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'receipt_number'), name='unique_receipt_per_pharmacy'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'created_at'], name='sales_sale__sale_id_c59f71_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['inventory_item'], name='sales_sale__invento_59270f_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitembatchallocation',
            index=models.Index(fields=['sale_item'], name='sales_sale__sale_it_abcc51_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitembatchallocation',
            index=models.Index(fields=['batch'], name='sales_sale__batch_i_bae22c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['pharmacy', 'created_at'], name='sales_stock_pharmac_22c4b6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['pharmacy', 'movement_type', 'created_at'], name='sales_stock_pharmac_96108b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['inventory_item', 'created_at'], name='sales_stock_invento_ffeb6a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['batch', 'created_at'], name='sales_stock_batch_i_28779b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['sale'], name='sales_stock_sale_id_27fe54_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='sales_stock_movemen_d6d1e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(('movement_type', 'SALE'), ('sale__isnull', False)), ('movement_type__in', ['RECEIVE', 'ADJUSTMENT', 'VOID']), _connector='OR'),
                name='sale_movement_has_sale_reference',
            ),
        ),
    ]
