# Generated by Django 5.1.15 on 2026-09-01 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customerreturn_inventoryhold_stockreconciliation_and_more'),
        ('pharmacy', '0011_add_rejection_reason_to_membership'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='sale_movement_has_sale_reference',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, choices=[('STOCK_COUNT_CORRECTION', 'Physical Count Correction'), ('DATA_ENTRY_ERROR', 'Data Entry Error'), ('FOUND', 'Lost Item Found'), ('ADJUSTMENT_OTHER', 'Other Adjustment'), ('DAMAGED_IN_STORAGE', 'Damaged in Storage'), ('DAMAGED_IN_DELIVERY', 'Damaged During Delivery'), ('QUALITY_ISSUE', 'Quality Issue'), ('PACKAGING_COMPROMISED', 'Packaging Compromised'), ('DAMAGE_OTHER', 'Other Damage'), ('NATURAL_EXPIRY', 'Natural Expiry'), ('DAMAGED_EXPIRY', 'Damaged - Also Expired'), ('RECALLED', 'Product Recalled'), ('MISSING_INVENTORY', 'Missing from Inventory'), ('SUSPECTED_THEFT', 'Suspected Theft'), ('UNKNOWN_LOSS', 'Unknown Loss'), ('OTHER', 'Other')], help_text='Reason for the movement', max_length=50),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='ID of parent transaction (CustomerReturn, StockReconciliation, InventoryHold)', null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('CUSTOMER_RETURN', 'Customer Return'), ('STOCK_RECONCILIATION', 'Stock Reconciliation'), ('INVENTORY_HOLD', 'Inventory Hold')], help_text='Type of parent transaction', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('VOID', 'Void/Reversal'), ('RECEIVE', 'Receive from Supplier'), ('ADJUSTMENT', 'Manual Adjustment'), ('DAMAGE', 'Damage'), ('EXPIRED', 'Expired Stock Write-off'), ('LOSS', 'Loss/Missing Stock'), ('CUSTOMER_RETURN', 'Customer Return'), ('STOCK_COUNT_CORRECTION', 'Stock Count Correction'), ('HOLD', 'Stock Hold/Quarantine'), ('RELEASE', 'Hold Release')], db_index=True, help_text='Type of stock movement', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity_change',
            field=models.IntegerField(help_text='Quantity change (negative for sales/damage/loss, positive for returns/receipts)'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='sales_stock_referen_b842d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(('movement_type', 'SALE'), ('sale__isnull', False)), ('movement_type__in', ['RECEIVE', 'ADJUSTMENT', 'VOID', 'DAMAGE', 'EXPIRED', 'LOSS', 'CUSTOMER_RETURN', 'STOCK_COUNT_CORRECTION', 'HOLD', 'RELEASE']), _connector='OR'),
                name='sale_movement_has_sale_reference',
            ),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(
                check=models.Q(('quantity_change', 0), _negated=True),
                name='movement_quantity_nonzero',
            ),
        ),
    ]
