# Generated by Django 5.0.6 on 2026-09-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_stockmovement_sale_movement_has_sale_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('PURCHASE', 'Purchase'), ('CUSTOMER_RETURN', 'Customer Return'), ('STOCK_RECONCILIATION', 'Stock Reconciliation'), ('INVENTORY_HOLD', 'Inventory Hold')], help_text='Type of parent transaction', max_length=50, null=True),
        ),
    ]
