# Generated by Django 5.1.15 on 2026-09-16

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_alter_pharmacybrand_brand_name'),
        ('sales', '0003_alter_stockmovement_reference_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Repayment amount received', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('POS', 'POS/Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('OTHER', 'Other')], default='CASH', help_text='Method used for this repayment', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='External reference or transaction ID', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer making the repayment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.customer')),
                ('pharmacy', models.ForeignKey(help_text='Pharmacy receiving the payment', on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='pharmacy.pharmacybrand')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='User who recorded the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, help_text='Optional sale this payment is linked to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payments', to='sales.sale')),
            ],
            options={
                'db_table': 'sales_customer_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('CREDIT_SALE', 'Credit Sale'), ('PAYMENT', 'Payment'), ('RETURN', 'Approved Return'), ('ADJUSTMENT', 'Adjustment'), ('VOID', 'Voided Sale Reversal')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Absolute amount for the transaction', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User that created the ledger event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer account affected by this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='sales.customer')),
                ('payment', models.ForeignKey(blank=True, help_text='Payment related to this ledger entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='sales.customerpayment')),
                ('pharmacy', models.ForeignKey(help_text='Pharmacy owning the account', on_delete=django.db.models.deletion.PROTECT, related_name='customer_ledger_entries', to='pharmacy.pharmacybrand')),
                ('sale', models.ForeignKey(blank=True, help_text='Sale related to this ledger entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='sales.sale')),
            ],
            options={
                'db_table': 'sales_customer_ledger_entry',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['customer', 'created_at'], name='sales_custo_customer_6fba0d_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['pharmacy', 'created_at'], name='sales_custo_pharmac_b0d4f5_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['customer', 'created_at'], name='sales_custo_customer_fcb231_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['pharmacy', 'created_at'], name='sales_custo_pharmac_7e2f19_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['sale'], name='sales_custo_sale_id_4523cf_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['payment'], name='sales_custo_payment_8c2bc7_idx'),
        ),
    ]
