# Generated by Django 5.1.15 on 2026-09-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_customerpayment_customerledgerentry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerledgerentry',
            new_name='sales_custo_custome_a53824_idx',
            old_name='sales_custo_customer_fcb231_idx',
        ),
        migrations.RenameIndex(
            model_name='customerledgerentry',
            new_name='sales_custo_pharmac_7131e6_idx',
            old_name='sales_custo_pharmac_7e2f19_idx',
        ),
        migrations.RenameIndex(
            model_name='customerledgerentry',
            new_name='sales_custo_sale_id_ae5c19_idx',
            old_name='sales_custo_sale_id_4523cf_idx',
        ),
        migrations.RenameIndex(
            model_name='customerledgerentry',
            new_name='sales_custo_payment_88e36c_idx',
            old_name='sales_custo_payment_8c2bc7_idx',
        ),
        migrations.RenameIndex(
            model_name='customerpayment',
            new_name='sales_custo_custome_2bcf88_idx',
            old_name='sales_custo_customer_6fba0d_idx',
        ),
        migrations.RenameIndex(
            model_name='customerpayment',
            new_name='sales_custo_pharmac_55c098_idx',
            old_name='sales_custo_pharmac_b0d4f5_idx',
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('POS', 'POS/Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('OTHER', 'Other'), ('DEBT', 'Debt / Credit')], help_text='How the sale was paid', max_length=20),
        ),
    ]
